### ISSUE TITLE
现在看可是异步加载，可以做一下按需加载的demo吗

### ISSUE THREAD

**Issue by luxueyan** [nightire/jspm-angular-demo#2]
跑了一下demo，看到的只是异步加载的过程，但是我想能不能做到，在router里面实现按需加载，就是controller和view都是用户点击了以后去加载的

**Comment by nightire** [comment]
@luxueyan 这不是 jspm 的责任，而是 Angular 1 自身的 module system 不支持按需加载。有一个 module 叫做 ozLazyLoad 的可以满足你的需求，自己搜一下吧。

记住，异步加载和按需加载是两回事。

**Comment by luxueyan** [comment]
恩，thanks 已经用了ozLazyLoad。可以满足我的需求！
