### ISSUE TITLE
关于模板加载

### ISSUE THREAD

**Issue by zh99998** [nightire/jspm-angular-demo#3]
看到目前这个是用 import !text 方式引入模板字符串的

``` javascript
import HomeTemplate from './home-template.html!text'
```

这与传统的 ui-router templateUrl 方式在效果上有什么区别吗? (例如加载顺序或者性能)

**Comment by nightire** [comment]
@zh99998 

`templateUrl` 指定的是一个目标的地址，Angular 解析此地址分为两种方式：
1. 如果有注册的 `templateCache` 服务，那么就用此服务内包含的同名的 cache，本质上这个 cache 就是一个对象，key 是地址，value 是 String 形式的模版。
2. 如果没有注册的 `templateCache` 服务，那么就向指定地址发送 HTTP 请求，返回的就是一个 HTML 文本。

无论是 1 还是 2，终究得到的还是 HTML 模版的 String 形式，这和你不用 `templateUrl` 而改用 `template` 达到的效果是没有什么区别的，只不过 `template` 你得把整个模版作为 value 写在那里罢了。很显然，这样既不方便编写，也不利于模版管理。

1 和 2 的区别就在于，1 是要把模版事先打包好（可以参考 Grunt/Gulp 下格式模版预编译插件），打包后的产出物是一个 Angular templateCache service，也就是一个 JavaScript 文件（里面包含了 k/v 形式的模版字符串），然后将此服务注入到 Angular App 即可。

这也就意味着，应用程序初始化时此文件必须要加载进来（否则依赖缺失），可以想象，如果你的模版非常非常多，那么这个 service 文件也会变得很大，而且即使里面的模版未必会每次用到也都得预先加载进来，于是就会造成初始请求的文件体积变大。

2 是异步加载的，用到哪里加载哪里。但问题是这些模版文件又在哪里呢？或许在 server 端，或许在 CDN 服务器上，总之你得让它（Angular）知道去哪里加载就是了。和 1 相比，减少了初始化的加载体积，但是增加了应用程序使用中需要请求的次数。

因此来说，各有利弊，看情况取舍罢了。

而 jspm 这种也是类似的，我们不用 `templateCache` service，但是也不需要像 `template` 那样把模版混在 JavaScript 代码里，而是折衷的用 text plugin 即时转换为文本插入到 `template` 的位置。鉴于 jspm 本身就是异步加载的，所以也可以得到随用随调的目的。

但是，同样的问题：在应用程序运行过程中，这些模版在哪里呢？
1. 如果采取异步加载模式，它们可以和其他静态资源一起散落在静态资源服务器内，只要 jspm 知道加载它们的路径就可以异步加载；
2. 如果采取打包模式（即 jspm bundle），那么本质上和 `templateCache` 没有太大的不同，因为所有的依赖不管是 HTML 模版也好还是其他的 JavaScript 文件都会被打包成一个文件（或者 n 个文件，取决于打包时的策略）

随着 HTTP／2 的临近，请求数目不会再是问题，并且未来的 web 是组件化的 web，每一个模版都是和自身对应的组件 bundle 在一起，所以像 Angular 1 那种 `templateCache` 统一打成一个包的模式会逐渐被淘汰。异步化的模块加载（无论什么资源）会成为主流，至于是不是像 jspm 这样写（`!text` 插件这样）倒也未必，目前只能这么做（包括 webpack 在内）而已。
